### ISSUE TITLE
stack sizes too large

### ISSUE THREAD

**Issue by KorGgenT** [Lorith/AdvancedGear-CDDA-Mod#1]
![image](https://user-images.githubusercontent.com/30208401/48804654-3ffbd480-ece3-11e8-8089-7452135882a2.png)

![image](https://user-images.githubusercontent.com/30208401/48804685-59048580-ece3-11e8-8843-81edda6769a8.png)

![image](https://user-images.githubusercontent.com/30208401/48804695-5efa6680-ece3-11e8-9248-946db81f84f6.png)

![image](https://user-images.githubusercontent.com/30208401/48804716-6457b100-ece3-11e8-92c5-8526a91f7dab.png)

tried on build 8194

**Comment by Lorith** [comment]
Oops, didn't notice there was an issue on github, it needs to give me some kind of notification.  Fixed this a few version back in case anyone is checking and wonders why this got closed.
