### ISSUE TITLE
Holster, shealh and magazine using is too fast

### ISSUE THREAD

**Issue by Adevald** [Lorith/AdvancedGear-CDDA-Mod#2]
I think there is some reasons, why it cant happen SO fast (like "draw_cost": 0,). It can be very fast, but i think it cant be instantly.

**Comment by Adevald** [comment]
15 steps i thinks is enough
(and your mod is incredibly marvellous. Some ideas (like mini-shoggoth store) make me enravishment. he-he.)

**Comment by Lorith** [comment]
Sorry for not responding, I don't check the issues unless someone points things out on discord.  The idea is that the various holders are not passive objects, they actively predict what you want and deliver it to you.  Or interface directly with your nervous system.  Not sure which I prefer, but in either case, it puts the object into your hands while you are already moving to do the action.  Example: hold hands into proper position to grip rifle and start moving head down to look through sight, rifle is placed into your hands before your head gets lined up to look through the scope.
